### ISSUE TITLE
"InvalidSequenceTokenException" thrown when used with multiple instances

### ISSUE THREAD

**Issue by billstron** [mirkokiefer/bunyan-cloudwatch#1]
When pushing logs from multiple machines to the same stream, the following error is encountered: 

```
{ 
  message: 'The given sequenceToken is invalid. The next expected sequenceToken is: 49540113951436919075269750063470750655650281036628124738',
  code: 'InvalidSequenceTokenException',
  time: Wed Jun 10 2015 19:36:17 GMT+0000 (UTC),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 
}
```

**Comment by nileshmali** [comment]
Hi,
Any plans to merge?
Thanks

**Comment by thalesfsp** [comment]
@mirkokiefer @billstron @nileshmali merge what? There's no PR :) Someone have the solution?

**Comment by Foxboron** [comment]
Any updates?

**Comment by thalesfsp** [comment]
Lol, project abandoned

**Comment by mirkokiefer** [comment]
There can always be only one source writing to a stream. I recommend adding e.g. the machine's IP address as a suffix to logStreamName.
Having multiple writers to the same stream would not be efficient as there would be a constant race condition for the sequenceToken.

**Comment by thalesfsp** [comment]
This recommendation is addressed in the README.md or somewhere?

**Comment by thalesfsp** [comment]
@mirkokiefer This recommendation is addressed in the `README.md` or somewhere?

**Comment by GlacianNex** [comment]
Proposed solution: https://github.com/mirkokiefer/bunyan-cloudwatch/pull/23

**Comment by GlacianNex** [comment]
#23 was merged in. Issue can be closed.

**Comment by amekkawi** [comment]
I agree with @mirkokiefer that only one source should write to a single unique Log Stream name.

[DescribeLogStream has a default limit of 5 transactions per account/region](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). While this is a soft limit, there is no limit to CreateLogStream requests and no limit to the number of Log Streams per Log Group.

If the Log Stream names are kept unique enough (i.e. include pid, time, random number, uuid, etc) then you will not encounter any throttling.

For AWS accounts that are focused in a single region, the throttling may also be difficult to diagnose/debug.

As I recall, the AWS docs aren't very good at making this known, so it might be better to update the bunyan-cloudwatch docs to mention this.

I talked about this a bit more at amekkawi/cwlogs-writable#8 as well.
