### ISSUE TITLE
Possible v3 of bunyan-cloudwatch

### ISSUE THREAD

**Issue by amekkawi** [mirkokiefer/bunyan-cloudwatch#21]
Thanks for the great library. I've recently rewritten bunyan-cloudwatch to overcome a few issues I encountered:

* `time` prop removed from bunyan JSON (#17)
* Unable to recover logs that failed to send (#19)
* Memory leak after onError (stream does not clear the queue and continues adding to it)

I also added support for [recovering from AWS errors](https://github.com/amekkawi/cwlogs-writable#recovering-from-aws-errors) and followed AWS limts on PutLogEvents (i.e. max 10000 log events and 1 MB per call) just to be safe.

Since I had a hard deadline I've published it as [cwlogs-writable](https://www.npmjs.com/package/cwlogs-writable).

However, I kept the constructor options (and methods to a degree) the same so it could act as a drop in replacement of bunyan-cloudwatch.

If you're still maintaining this library, I'd love to collaborate to try to work these changes into bunyan-cloudwatch.

Thanks again!

**Comment by jerroydmoore** [comment]
Thanks for people to your forked copy. I'm not sure if this project is currently maintained, but I have run into issues using bunyan-cloudwatch. I was wondering why you did not submit a PR? Also, I've taken a look at your commit history, and it appears you've erased this project's git history. Any reason why you've done this?

**Comment by amekkawi** [comment]
cwlogs-writable is a complete rewrite of bunyan-cloudwatch and not a fork, so the commit history isn't shared.

To make it as much of a drop-in replacement as possible, I used the same names for options, properties and methods.

However, since it is a rewrite a simple PR wouldn't work. I opened this issue in case some of the changes/fixes implemented in cwlogs-writable could be ported over to bunyan-cloudwatch.

**Comment by jerroydmoore** [comment]
Thanks for the clarification!

**Comment by mirkokiefer** [comment]
@amekkawi I have a bit more bandwith for open source work in the next while - would be happy to work on improving this library.

**Comment by amekkawi** [comment]
Hi @mirkokiefer sorry I missed your response. Still have some bandwidth?
