### ISSUE TITLE
JSON.stringify crashes application

### ISSUE THREAD

**Issue by oliversalzburg** [mirkokiefer/bunyan-cloudwatch#26]
Because this module passes log input through `JSON.stringify` before passing it to bunyan, it runs the high risk of causing an exception due to the circular structure of the object passed to the logger.

[bunyan itself avoids this problem](https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L89), so all our logging calls were fine before we introduced this module.

IMHO, at the very least, the same stringification approach from bunyan should be utilized.

**Comment by mirkokiefer** [comment]
Thanks for raising this, I never ran into this issue but you definitely don't want to be thinking too much about what data you are throwing at a logger. Will look into using the same approach bunyan uses.

**Comment by mirkokiefer** [comment]
@oliversalzburg let me know if this solved your issue too.

**Comment by oliversalzburg** [comment]
Awesome. Thanks for the quick fix. Sadly I can't verify as we realized that our approach to logging was problematic and we're now no longer directly interfacing with CloudWatch.
